name: 2. Manual Upload to freee

on:
  # 手動で実行できるようにする
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'Upload target artifact name (e.g., freee-import-file)'
        required: true
        default: 'freee-import-file'

jobs:
  upload-to-freee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.artifact_name }}
          path: ./upload_target

      - name: List downloaded files
        run: |
          echo "Listing files in the artifact directory:"
          ls -R ./upload_target

      - name: Install dependencies and browsers
        run: |
          python -m pip install --upgrade pip
          pip install -r freee-upload/requirements.txt
          playwright install --with-deps

      - name: Run Upload Script
        env:
          FREEE_EMAIL: ${{ secrets.FREEE_EMAIL }}
          FREEE_PASSWORD: ${{ secrets.FREEE_PASSWORD }}
        run: |
          # Find the CSV file in the downloaded artifact directory
          FILE_PATH=$(find ./upload_target -name "*.csv" -print -quit)
          if [ -z "$FILE_PATH" ]; then
            echo "Error: No CSV file found in the downloaded artifact."
            exit 1
          fi
          echo "Uploading file: $FILE_PATH"
          python freee-upload/upload.py --file "$FILE_PATH"
