 1 name: 2. Manual Freee Upload
    2
    3 on:
    4   # 手動実行のみ
    5   workflow_dispatch:
    6
    7 jobs:
    8   upload-to-freee:
    9     runs-on: ubuntu-latest
   10     steps:
   11       - name: Checkout repository
   12         uses: actions/checkout@v4
   13
   14       - name: Set up Python
   15         uses: actions/setup-python@v5
   16         with:
   17           python-version: '3.11'
   18
   19       - name: Install dependencies
   20         run: |
   21           python -m pip install --upgrade pip
   22           pip install -r freee-upload/requirements.txt
   23
   24       - name: Download Artifact
   25         uses: actions/download-artifact@v4
   26         with:
   27           name: freee-import-file
   28           path: ./temp-data
   29
   30       - name: Find downloaded file
   31         id: find_file
   32         run: |
   33           file_path=$(find ./temp-data -name "freee_import_sales_data_*.csv")
   34           echo "file_path=$file_path" >> $GITHUB_OUTPUT
   35
   36       - name: Run Upload Script
   37         env:
   38           FREEE_EMAIL: ${{ secrets.FREEE_EMAIL }}
   39           FREEE_PASSWORD: ${{ secrets.FREEE_PASSWORD }}
   40         run: python freee-upload/upload.py --file ${{ steps.find_file.outputs.file_path }}
